version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.0
    ports:
      - '5432:5432'
    volumes:
      - cats-api-pg:/data/postgres
      - ./actions/postgres:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=cats-api'
      # - "POSTGRES_INITDB_ARGS=cats-api"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - /tmp/pgadmin:/root/.pgadmin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  cats-api-pg:
